### ISSUE TITLE
是否支持存取prost-build构建的对象？如果支持请给一个演示代码，多谢

### ISSUE THREAD

**Issue by i18nsite** [yangkx1024/MMKV#7]
如题，如果不支持，可以考虑加一个feature=prost启用支持

主要是我看 https://www.yangkx.net/posts/rust-mmkv-1/ 这里用到了prost

**Comment by yangkx1024** [comment]
> 如题，如果不支持，可以考虑加一个feature=prost启用支持
> 
> 主要是我看 https://www.yangkx.net/posts/rust-mmkv-1/ 这里用到了prost

不是很确定你的意思，据我了解prost-build是一个编译proto到rust代码的crate，这里说的“存取prost-build构建的对象”具体指什么？我的博文里面提到的是我目前是使用的protobuf来编码需要写到文件的数据。如果是指存取序列化的对象的话，`MMKV::put_byte_array`可以用来存二进制数组。

**Comment by i18nsite** [comment]
https://docs.rs/prost/latest/prost/trait.Message.html

我意思是加一个类似MMKV::put_byte_array的接口，比如

```
MMKV::put_proto(key: impl AsRef<[u8]>, val:impl prost::Message)
MMKV::get_proto<Msg:prost::Message>(key: impl AsRef<[u8]>)->Msg

```

这样对于有需求的下游，可以简化很多代码

**Comment by yangkx1024** [comment]
我这里的MMKV库的API设计只针对通用数据类型，不会涉及也没办法覆盖所有的调用者的数据结构，所以针对具体类型加API是不合理的。
查了下prost::Message是有个序列化为byte数组的方法的：
https://docs.rs/prost/latest/prost/trait.Message.html#method.encode_to_vec
针对你的需求，直接调用`Message::encode_to_vec`转为`Vec[u8]`再调用`MMKV::put_byte_array`应该就可以。

**Comment by i18nsite** [comment]
因为我看到这里写的：
https://www.yangkx.net/posts/rust-mmkv-1/
使用[protobuf](https://protobuf.dev/)来序列化数据


如果我原本的数据就是protobuf的类型，按照现在的流程是先序列化一次到Vec<u8>，再序列化一次Vec<u8>，感觉多了一步序列化，增加了时间和空间成本，也没简化什么操作。

API设计只针对通用数据类型，所以我感觉，考虑加一个feature=prost启用支持，如果不需要，就不启用这个feature

**Comment by yangkx1024** [comment]
实际上从抽象的角度去看，上层调用也不该过多考虑底层实现依赖的数据结构，这种耦合造成的结果就是任何底层实现的变动（比如这里底层的protbuf将来有一天可能变成flatbuffer甚至自定义数据结构实现），都会造成上层调用的不兼容。所以我们需要针对抽象的通用数据结构来设计。如果这里实在性能敏感，那我更建议你fork一份针对你们自己的场景去适配改造。
